"""
Capital allocation manager with deterministic safety clamps.
Safeguards cross-section rebalancing proposals generated by the Axel Prime Overseer.
"""

from dataclasses import dataclass

from axel.core.contracts import AllocationProposal
from axel.risk.limits import LIMITS, RiskLimits


@dataclass(frozen=True)
class AllocationDecision:
    approved: bool
    from_section: str
    to_section: str
    requested_pct: float
    approved_pct: float
    approved_amount_usd: float
    reason: str | None = None


class CapitalAllocator:
    """
    Validates and clamps capital rebalancing proposals between sections.
    Rejects proposals that attempt to reallocate more than 5% of total portfolio capital per cycle.
    """

    def __init__(self, limits: RiskLimits = LIMITS):
        self.limits = limits

    def evaluate_proposal(
        self,
        proposal: AllocationProposal,
        total_portfolio_nav: float,
        from_section_capital: float,
        min_section_reserve_pct: float = 0.10,
    ) -> AllocationDecision:
        """
        Pure function: evaluates an AllocationProposal.
        Excess shifts (> 5% of total portfolio) are rejected to prevent rapid destabilization.
        """
        if total_portfolio_nav <= 0.0:
            return AllocationDecision(
                approved=False,
                from_section=proposal.from_section.value,
                to_section=proposal.to_section.value,
                requested_pct=proposal.pct_of_total,
                approved_pct=0.0,
                approved_amount_usd=0.0,
                reason="Invalid total portfolio NAV",
            )

        if proposal.from_section == proposal.to_section:
            return AllocationDecision(
                approved=False,
                from_section=proposal.from_section.value,
                to_section=proposal.to_section.value,
                requested_pct=proposal.pct_of_total,
                approved_pct=0.0,
                approved_amount_usd=0.0,
                reason="Source and destination sections are identical",
            )

        # 1. Hard cap: Max 5% of total capital per cycle
        if proposal.pct_of_total > self.limits.MAX_REALLOCATION_PCT_PER_CYCLE + 1e-6:
            return AllocationDecision(
                approved=False,
                from_section=proposal.from_section.value,
                to_section=proposal.to_section.value,
                requested_pct=proposal.pct_of_total,
                approved_pct=0.0,
                approved_amount_usd=0.0,
                reason=(
                    f"REALLOCATION EXCEEDS CYCLE CAP: requested {proposal.pct_of_total:.2%} > "
                    f"max allowed {self.limits.MAX_REALLOCATION_PCT_PER_CYCLE:.2%}. Rejected."
                ),
            )

        shift_amount_usd = proposal.pct_of_total * total_portfolio_nav

        # 2. Check source section reserve requirement
        min_reserve_usd = total_portfolio_nav * min_section_reserve_pct
        if (from_section_capital - shift_amount_usd) < min_reserve_usd:
            return AllocationDecision(
                approved=False,
                from_section=proposal.from_section.value,
                to_section=proposal.to_section.value,
                requested_pct=proposal.pct_of_total,
                approved_pct=0.0,
                approved_amount_usd=0.0,
                reason=(
                    f"SOURCE RESERVE BREACH: Reallocation of ${shift_amount_usd:,.2f} would leave "
                    f"{proposal.from_section.value} below minimum reserve (${min_reserve_usd:,.2f})."
                ),
            )

        return AllocationDecision(
            approved=True,
            from_section=proposal.from_section.value,
            to_section=proposal.to_section.value,
            requested_pct=proposal.pct_of_total,
            approved_pct=proposal.pct_of_total,
            approved_amount_usd=round(shift_amount_usd, 2),
            reason="Approved within cycle reallocation bounds",
        )
